DROP TABLE
IF EXISTS sys_userRole;

CREATE TABLE
IF NOT EXISTS sys_userRole (
	id VARCHAR (40) NOT NULL PRIMARY KEY COMMENT 'ID',
	user_id VARCHAR (40) NOT NULL COMMENT '用户ID',
	role_id VARCHAR (40) NOT NULL COMMENT '角色ID'
) COMMENT '用户角色关系表' ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;