DROP TABLE
IF EXISTS sys_roleResource;

CREATE TABLE
IF NOT EXISTS sys_roleResource (
	id VARCHAR (40) NOT NULL PRIMARY KEY COMMENT 'ID',
	role_id VARCHAR (40) NOT NULL COMMENT '角色ID',
	resource_id VARCHAR (40) NOT NULL COMMENT '资源ID'
) COMMENT '角色资源关系表' ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;